spring.application.name=firmaec-backend
server.servlet.context-path=/firmaec-api

# Límite de tamaño de peticiones (certificados + PDFs en Base64)
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-http-post-size=20971520

# URL oficial del endpoint transversal de FirmaEC (Ajustar si tienen un ambiente de pruebas de MINTEL)
firmaec.api.url=https://api.firmadigital.gob.ec/api/appfirmardocumento

# NOTA PRODUCCIÓN: Habilitar HTTPS con certificado SSL
# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=changeit
# server.ssl.key-store-type=PKCS12