spring.application.name=firmaec-backend
server.servlet.context-path=/firmaec-api

# URL oficial del endpoint transversal de FirmaEC (Ajustar si tienen un ambiente de pruebas de MINTEL)
firmaec.api.url=https://api.firmadigital.gob.ec/api/appfirmardocumento